#!/usr/bin/env bash
# Ensure that the script is run as root to have permission to list all sockets.

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Use netstat to display TCP and UDP ports
netstat -lp